// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetColumns() {
  return window['go']['biz']['App']['GetColumns']();
}

export function Pull() {
  return window['go']['biz']['App']['Pull']();
}

export function Start(arg1) {
  return window['go']['biz']['App']['Start'](arg1);
}
