// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {biz} from '../models';
import {monitor} from '../models';

export function GetColumns():Promise<Array<biz.Column>>;

export function GetFiles():Promise<Array<string>>;

export function LoadFile(arg1:string):Promise<void>;

export function Pull():Promise<Array<biz.Msg>>;

export function Start(arg1:number):Promise<void>;

export function Start1():Promise<monitor.Rule>;

export function Start3():Promise<monitor.Filter>;
