// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {biz} from '../models';

export function GetColumns():Promise<Array<biz.Column>>;

export function Pull():Promise<Array<biz.Msg>>;

export function Start(arg1:number):Promise<void>;
